name: "Slack Approval Action"
description: "Sends a Slack message with Approve/Reject buttons"
inputs:
  slack_token:
    description: "Slack Bot Token"
    required: true
  channel_id:
    description: "Slack Channel ID"
    required: true
  image_tag:
    description: "Docker image tag"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
